### ISSUE TITLE
Code examples in reporitory do not match code used in book

### ISSUE THREAD

**Issue by thmsklngr** [PacktPublishing/Learning-jQuery-3#3]
Hi,

I just bought the book "Learning jQuery 3 - fifth edition" and downloaded the code examples directly from this repository. This is actually  disappointing since the code in the repository does not match the code used in the book.

Most visible difference is the usage of using the  `$(documen).ready()` function. In the book `$(() => {})`is used instead.

True is that the code is working with no difference, but usually I'd rather expect the code to be similar to the book.

Regards, Thomas

**Comment by mosesontheweb** [comment]
Here's another example, listing 4.15:
from the book:
`javascript
$(() => {
  const sizeMap = {
    'switcher-small': n => n / 1.4,
    'switcher-large': n => n * 1.4,
    'switcher-default': () => defaultSize
  };

  const $speech = $('div.speech');
  const defaultSize = parseFloat($speech.css('fontSize'));

  $('#switcher button')
    .click((e) => {
      const num = parseFloat($speech.css('fontSize'));
      $speech.animate({
        fontSize: `${sizeMap[e.target.id](num)}px`
      });
    });
}); `

from the listing in the repository:
`javascript
$(() => {
  const sizeMap = {
    'switcher-small': n => n / 1.4,
    'switcher-large': n => n * 1.4,
    'switcher-default': () => defaultSize
  };

  const $speech = $('div.speech');
  const defaultSize = parseFloat($speech.css('fontSize'));

  $('#switcher button')
    .click((e) => {
      const num = parseFloat($speech.css('fontSize'));
      $speech.animate({
        fontSize: `${sizeMap[e.target.id](num)}px`
      });
    });
}); 
`
The result remains the same, but the code is totally different ...

**Comment by thmsklngr** [comment]
Sorry, wrong issue, took the worng directory. Used the code from missing_code.tar.gz.
